devErrorsEnabled:true
debuggingEnabled:false
debugHeaderEnabled:false
loggingEnabled:true
logDirectory:\apps\local\transcript\logs
maxTotalLogFileSizeInKB:100000
maxLogFiles:50
nodeProcessCommandLine:C:\node\8.11.4\node.exe --max-old-space-size=2500
node_env:production
