devErrorsEnabled:false
debuggingEnabled:false
loggingEnabled:true
logDirectory:c:\apps\local\jobCollectionService\logs
nodeProcessCommandLine:C:\Program Files (x86)\nodejs\node.exe
node_env:production