systemLog:
   destination: file
   path: c:\data\log\mongod.log
   logAppend: true
storage:
   dbPath: c:\data\db
   journal:
      enabled: true
   mapv1:
      smallFiles: true
setParameter:
   enableLocalhostAuthBypass: false
net:
   bindIp: 127.0.0.1
   port: 27017
replication:
   replSetName: rs1
