systemLog:
   destination: file
   path: c:\data\log2\mongod.log
   logAppend: true
storage:
   dbPath: c:\data\db2
   journal:
      enabled: true
   mapv1:
      smallFiles: true
setParameter:
   enableLocalhostAuthBypass: false
net:
   bindIp: 127.0.0.1
   port: 27018
replication:
   replSetName: rs1
